In [1]:
!nvidia-smi

Mon Nov  4 20:22:19 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:05:00.0  On |                  N/A |
| 27%   47C    P8    11W / 250W |     91MiB / 11175MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:06:00.0 Off |                  N/A |
| 26%   47C    P8    10W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  G

In [2]:
import torch
from torch import nn

torch.cuda.is_available()

True

In [3]:
torch.cuda.device_count()

4

In [4]:
torch.cuda.current_device()

0

In [5]:
torch.cuda.get_device_name(0)

'GeForce GTX 1080 Ti'

In [7]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [9]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [10]:
x.device

device(type='cuda', index=0)

In [14]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
x

tensor([1, 2, 3], device='cuda:0')

In [15]:
y = x**2
y

tensor([1, 4, 9], device='cuda:0')

In [16]:
net  = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [17]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [19]:
x = torch.rand(2, 3).cuda()
net(x)

tensor([[0.4039],
        [0.3982]], device='cuda:0', grad_fn=<AddmmBackward>)